name: ride_hailing_app
description: A ride-hailing application similar to Bolt.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # HTTP & API # Network & API
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2

  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^13.2.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_polyline_points: ^2.0.0
  


  # WebSockets for real-time features
  web_socket_channel: ^3.0.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # Authentication
  local_auth: ^2.1.8

  # Notifications
  flutter_local_notifications: ^14.1.1
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  
  # Utilities
  logger: ^2.0.2+1
  url_launcher: ^6.2.4
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  image_picker: ^1.0.7
  permission_handler: ^11.1.0
  flutter_dotenv: ^5.1.0
  uuid: ^4.2.2
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^8.0.3

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  mockito: ^5.4.4
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - .env 
 
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
